from .Animal import Animal
from .Alligator import Alligator
from .Gecko import Gecko
from .Hognose import Hognose
from .Skink import Skink
from .Snork import Snork
from .Axolotl import Axolotl
from .Catfish import Catfish
from .Goldfish import Goldfish
from .Octopus import Octopus
from .Shark import Shark
from .Cougar import Cougar
from .Donkey import Donkey
from .Goose import Goose
from .Horse import Horse
from .Llama import Llama